app/main/__init__.py
from flask import Blueprint
from ..models import Video
from .controller import MainController

# create a new blueprint for the main features
main_bp = Blueprint('main', __name__)

# initialize the main controller
main_controller = MainController()


# populate the videos table in the db
@main_bp.before_request
def before_request():
    # fetch and save youtube videos
    print('Fetching videos from youtube...')
    main_controller.fetch_yt_videos(main_controller.default_kw)
    print('Fetched videos from youtube.')
    main_controller.save_videos()

from . import views

app/main/controller.py
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from ..models import Video
from flask import flash
import os


class MainController:
    """Manages the business logic of the main blueprint."""

    DEVELOPER_KEY = os.environ.get('YOUTUBE_API_KEY')
    YOUTUBE_API_SERVICE_NAME = 'youtube'
    YOUTUBE_API_VERSION = 'v3'

    def __init__(self):
        self.youtube_build = build(
            self.YOUTUBE_API_SERVICE_NAME, self.YOUTUBE_API_VERSION,
            developerKey=self.DEVELOPER_KEY)
        self.videos = []
        self.default_kw = 'Mental Energy'

    def fetch_yt_videos(self, search_kw):
        """Fetch youtube videos related to the search keyword."""
        try:
            # fetch the items matching the query keyword passed.
            search_res = self.youtube_build.search().list(
                q=search_kw, part='id,snippet'
            ).execute()

            for search_item in search_res.get('items', []):
                if search_item['id']['kind'] == 'youtube#video':
                    video_data = {}

                    # extract thumbnail url
                    thumbnail = search_item.get('snippet', {}).get(
                        'thumbnails', {}).get('default')
                    if thumbnail:
                        video_data['thumbnail'] = thumbnail['url']
                    
                    # extract video url
                    video_url = search_item.get('id', {}).get('videoId')
                    if video_url:
                        video_data['url'] = 'https://www.youtube.com/embed/' + video_url
                    
                    # extract video title
                    video_title = search_item.get('snippet', {}).get('title')
                    if video_title:
                        video_data['title'] = video_title
                    
                    # extract video description
                    video_description = search_item.get('snippet', {}).get(
                        'description')
                    if video_description:
                        video_data['desc'] = video_description
                    # add video to the list
                    self.videos.append(video_data)
        except Exception as e:
            message = str(e)

            if type(e) is HttpError:
                message = e.reason

            flash(message, 'error')
    
    def get_videos(self):
        """Extract all videos from the database."""
        self.videos = Video.get_all()
        return self.videos
    
    def save_videos(self):
        """Save all videos to the database if they don't already exist."""
        for video_data in self.videos:
            try:
                if not Video.get_one_by(url=video_data['url']):
                    new_video = Video(**video_data)

                    # save new video
                    new_video.save()
                    print(f'Saved video: {new_video.title}')
            except HttpError as e:
                print(f'Could not save video: {str(e)}.')

app/main/views.py
from . import main_bp
from flask import render_template
from ..models import Video
from flask_login import login_required


@main_bp.get('/')
def index():
    return render_template('main/index.html')


@main_bp.get('/mental-energy')
def mental_energy():
    # fetch videos that discussed mental energy from db
    videos = Video.get_by_attrs(keyword='Mental Energy')

    return render_template('main/mental-energy.html', videos=videos)


@main_bp.route('/physical-energy', methods=['GET', 'POST'])
@login_required
def physical_energy():
    return render_template('main/physical-energy.html')

app/templates/main/index.html
{% extends "base.html" %}
{% block tab_title %}Home Page{% endblock %}
{% block stylesheets %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
    <div class="container">
        <section class="hero">
            <div class="hero-content">
                <h1>Get the Most Out of Your Energy</h1>
                <p>Manage your mental and physical energy to maximize productivity and well-being.</p>
                {% if current_user.is_authenticated %}
                    <a href="{{url_for('auth.logout')}}" class="btn">Logout</a>
                {% else %}
                    <a href="{{url_for('auth.index')}}" class="btn">Sign Up</a>
                {% endif %}
            </div>
        </section>
        <section class="features">
            <a href="{{url_for('main.mental_energy')}}">
            <div class="feature">
                <img src="{{url_for('static', filename='images/mental-energy-icon.avif')}}"
                alt="Conservation of Mental Energy">
                <h2>Conservation of Mental Energy</h2>
                <p>Discover activities that waste mental energy and receive tips to increase efficiency.</p>
            </div>
            </a>
            <div class="feature">
            <a href="{{url_for('main.physical_energy')}}">
                <img src="{{url_for('static', filename='images/physical-energy-icon.avif')}}"
                alt="Conservation of Physical Energy">
                <h2>Conservation of Physical Energy</h2>
                <p>Track and monitor your daily activities, get recommendations, and improve your physical energy.</p>
            </a>
            </div>
            <div class="feature">
            <a href="#time-management">
                <img src="{{url_for('static', filename='images/time-management-icon.avif')}}" alt="Conservation of Time">
                <h2>Conservation of Time</h2>
                <p>Organize and plan your activities, achieve growth in every aspect of your life, and create free time for self-improvement.</p>
            </a>
            </div>
        </section>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
{% endblock %}

app/templates/main/mental-energy.html
{% extends "base.html" %}
{% block tab_title %}Mental Energy{% endblock %}
{% block stylesheets %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
    <section class="videos-section">
        <h2>Videos</h2>
        <div class="videos-container">
        {% for video in videos %}
            <div class="video">
                <iframe width="560" height="315" src="{{video.url}}" title="{{video.title}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                <h3>{{video.title|safe}}</h3>
                <p>{{video.desc}}</p>
            </div>
        {% endfor %}
        </div>
    </section>
    <section class="tips">
        <h2>Tips</h2>
        <ul>
            <li>
                <img src="{{url_for('static', filename='images/breathing-exercise.avif')}}" alt="Image 1">
                <span>Practice deep breathing exercises to reduce stress and calm your mind.</span>
            </li>
            <li>
                <img src="{{url_for('static', filename='images/physical-energy-icon.avif')}}" alt="Image 2">
                <span>Engage in regular physical exercise to boost your mood and improve mental well-being.</span>
            </li>
            <li>
                <img src="{{url_for('static', filename='images/self-care.avif')}}" alt="Image 3">
                <span>Prioritize self-care activities such as getting enough sleep and practicing relaxation techniques.</span>
            </li>
        </ul>
    </section>
{% endblock %}

app/templates/main/physical-energy.html
{% extends "base.html" %}
{% block tab_title %}Physical Energy{% endblock %}
{% block stylesheets %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
    <div class="physical-container">
        <section class="physical-health">
            <h2>Physical Health</h2>

            <div class="daily-tracking">
                <div class="image-container">
                    <img src="{{url_for('static', filename='/images/time-audit.jpg')}}" alt="activities">
                </div>
                <div class="form-container">
                <div class="form-header">
                    <h3 class="form-heading">Daily Activity Tracking</h3>
                </div>
                <form id="time-audit-form">
                    <div class="form-group">
                    <label for="activity-input">Activity:</label>
                    <input type="text" id="activity-input" name="activity_name" required>
                    </div>
            
                    <div class="form-group">
                    <label for="time-input">Time spent (in minutes):</label>
                    <input type="number" id="time-input" name="time" min="0" required>
                    </div>
                    
                    <div class="form-group">
                    <label for="location-input">Location:</label>
                    <input type="text" id="location-input" name="location" required>
                    </div>
                    
                    <div class="form-group">
                    <label for="distance-input">Distance (in miles):</label>
                    <input type="number" id="distance-input" name="distance" min="0" step="0.01" required>
                    </div>
                    <button type="submit">Submit</button>
                </form>
                </div>
            </div>

            <div class="activity-prompts">
                <h3>Activity Prompts</h3>
                <p>Receive prompts every 30 minutes to record your activities:</p>
                <div id="activity-prompt">
                <!-- Display the current activity prompt here -->
                <p id="current-activity-prompt">Prompt: Stretch your legs and take a short walk.</p>
                </div>
                <button id="record-activity-btn">Record Activity</button>
            </div>

            <div class="activity-recommendations">
                <h3>Activity Recommendations</h3>
                <p>Get recommendations based on your time audit, using the Eisenhower Matrix:</p>
                <div id="recommendations">
                <!-- Display the recommendations based on the time audit here -->
                </div>
            </div>

            <div class="recommendations-container">
            <div class="morning-routines">
                <h3>Morning Routines</h3>
                <p>Get suggestions for light morning routines to awaken your mental and physical states:</p>
                <div id="morning-routines">
                <!-- Display the suggestions for morning routines here -->
                <ul>
                    <li>
                    <div class="recommendation-box">
                        <img src="{{url_for('static', filename='/images/Stretching-exercise.jpg')}}" alt=""> Stretching exercises
                    </div>
                    </li>
                    <li>
                    <div class="recommendation-box">
                        <img src="{{url_for('static', filename='/images/Meditation or mindfulness practice.jpg')}}" alt=""> Meditation or mindfulness practice
                    </div>
                    </li>
                    <li>
                    <div class="recommendation-box">
                        <img src="{{url_for('static', filename='/images/Light cardio workout.jpg')}}" alt=""> Light cardio workout
                    </div>
                    </li>
                </ul>
                </div>
            </div>

            <div class="food-recommendations">
                <h3>Food Recommendations</h3>
                <p>Receive food recommendations based on your work assessment survey:</p>
                <div id="food-recommendations">
                <!-- Display the food recommendations based on the survey here -->
                <ul>
                    <li>
                    <div class="recommendation-box">
                        <img src="{{url_for('static', filename='/images/Grilled chicken salad.jpg')}}" alt=""> Grilled chicken salad
                    </div>
                    </li>
                    <li>
                    <div class="recommendation-box">
                        <img src="{{url_for('static', filename='/images/Vegetable stir-fry with tofu.jpg')}}" alt=""> Vegetable stir-fry with tofu
                    </div>
                    </li>
                    <li>
                    <div class="recommendation-box">
                        <img src="{{url_for('static', filename='/images/Quinoa and roasted vegetable bowl.jpg')}}" alt=""> Quinoa and roasted vegetable bowl
                    </div>
                    </li>
                </ul>
                </div>
                </div>
                </div>
            </div>

        </section>
    </div> 
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
{% endblock %}